In [4]:
import zenidatasdk as zd
import alphalens
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import time
import os

# 检查版本
print(f"ZeniData SDK版本: {zd.__version__}")

# 测试导入主要模块
from zenidatasdk import Client
print("✅ 所有模块导入成功")

# 创建客户端（测试基础功能）
client = zd.Client()
print("✅ 客户端创建成功")

# 登录账号，初始化 client 对象
client = zd.Client(
    username = "3191883175@qq.com",
    password = "Abc123456", 
    base_url = "http://192.168.1.100:8000"
)
print("✅ 登录成功")

ZeniData SDK版本: 2.0.5
✅ 所有模块导入成功
✅ 客户端创建成功
✅ 登录成功

In [5]:
tmp_Dataset_path = rf"C:\Users\zy\Desktop\tmp_Dataset"          # 临时数据集路径
cutoff_date = rf"2026-04-10"                                    # 截至日期

cutoff_date_path = os.path.join(tmp_Dataset_path, cutoff_date)  # 临时数据集的 cutoff_date 路径
os.makedirs(cutoff_date_path, exist_ok = True)

In [6]:
symbols_df_path = os.path.join(cutoff_date_path, rf"symbols.csv")   # 定义截止日期的股票列表路径
if not os.path.exists(symbols_df_path):
    symbols_df = client.get_symbols_df(end_date = cutoff_date)      # 如果路径为空，获取截止日期的股票列表
    symbols_df.to_csv(symbols_df_path, index = False)               # 并保存

symbols_df = pd.read_csv(symbols_df_path)                           # 定义股票列表 DataFrame 对象
symbols_df

,symbol,name,short_name,start_date,end_date,update_time
0,000001.XSHE,平安银行,PAYH,1991-04-03,2200-01-01,2026-04-10 15:15:01.083
1,000002.XSHE,万科A,WKA,1991-01-29,2200-01-01,2026-04-10 15:15:01.083
2,000004.XSHE,*ST国华,*STGH,1990-12-01,2200-01-01,2026-04-10 15:15:01.083
3,000005.XSHE,ST星源,STXY,1990-12-10,2024-04-25,2026-04-10 15:15:01.083
4,000006.XSHE,深振业A,SZYA,1992-04-27,2200-01-01,2026-04-10 15:15:01.083
...,...,...,...,...,...,...
5489,688816.XSHG,易思维,YSW,2026-02-11,2200-01-01,2026-04-10 15:15:01.083
5490,688818.XSHG,电科蓝天,DKLT,2026-02-10,2200-01-01,2026-04-10 15:15:01.083
5491,688819.XSHG,天能股份,TNGF,2021-01-18,2200-01-01,2026-04-10 15:15:01.083
5492,688981.XSHG,中芯国际,ZXGJ,2020-07-16,2200-01-01,2026-04-10 15:15:01.083
5493,689009.XSHG,九号公司,JHGS,2020-10-29,2200-01-01,2026-04-10 15:15:01.083

In [7]:
for index, item in symbols_df.iterrows():       # 遍历指定截止日期的 股票列表DataFrame
    symbol = item['symbol']                     # 赋值股票代码等变量
    name = item['name']
    short_name = item['short_name']
    start_date = item['start_date']
    end_date = item['end_date']
    print(f"{index} {symbol} {name} {short_name}")

    
    bars_df_path = os.path.join(cutoff_date_path, rf"{symbol}.csv") # 定义指定股票的文件路径
    if not os.path.exists(bars_df_path):                            # 若路径为空
        bars_df = client.get_bars(                                  # 则获取股票 OHLCV数据
            symbol = symbol, 
            start_date = start_date, 
            end_date = cutoff_date, 
            frequency='1d', 
            adjust_type='post', 
            market='cn_stock'
        )
        bars_df.to_csv(bars_df_path, index = False)                 # 并写入指定路径

0 000001.XSHE 平安银行 PAYH
1 000002.XSHE 万科A WKA
2 000004.XSHE *ST国华 *STGH
3 000005.XSHE ST星源 STXY
4 000006.XSHE 深振业A SZYA
5 000007.XSHE 全新好 QXH
6 000008.XSHE 神州高铁 SZGT
7 000009.XSHE 中国宝安 ZGBA
8 000010.XSHE 美丽生态 MLST
9 000011.XSHE 深物业A SWYA
10 000012.XSHE 南玻A NBA
11 000014.XSHE 沙河股份 SHGF
12 000016.XSHE 深康佳A SKJA
13 000017.XSHE 深中华A SZHA
14 000018.XSHE 神城A退 SCAT
15 000019.XSHE 深粮控股 SLKG
16 000020.XSHE 深华发A SHFA
17 000021.XSHE 深科技 SKJ
18 000022.XSHE 深赤湾A SCWA
19 000023.XSHE *ST深天 *STST
20 000024.XSHE 招商地产 ZSDC
21 000025.XSHE 特力A TLA
22 000026.XSHE 飞亚达 FYD
23 000027.XSHE 深圳能源 SZNY
24 000028.XSHE 国药一致 GYYZ
25 000029.XSHE 深深房A SSFA
26 000030.XSHE 富奥股份 FAGF
27 000031.XSHE 大悦城 DYC
28 000032.XSHE 深桑达A SSDA
29 000033.XSHE 新都退 XDT
30 000034.XSHE 神州数码 SZSM
31 000035.XSHE 中国天楹 ZGTY
32 000036.XSHE 华联控股 HLKG
33 000037.XSHE 深南电A SNDA
34 000038.XSHE 大通退 DTT
35 000039.XSHE 中集集团 ZJJT
36 000040.XSHE *ST旭蓝 *STXL
37 000042.XSHE 中洲控股 ZZKG
38 000043.XSHE 中航善达 ZHSD
39 000045.XSHE 深纺织A SFZA
40 000046.XSHE *ST泛海 *STFH
41 000048.XSHE 京基智农 JJZN
42 000049.XSHE 德赛电池 DSDC
43 000050.XSHE 深天马A STMA
44 000055.XSHE 方大集团 FDJT
45 000056.XSHE 皇庭国际 HTGJ
46 000058.XSHE 深赛格 SSG
47 000059.XSHE 华锦股份 HJGF
48 000060.XSHE 中金岭南 ZJLN
49 000061.XSHE 农产品 NCP
50 000062.XSHE 深圳华强 SZHQ
51 000063.XSHE 中兴通讯 ZXTX
52 000065.XSHE 北方国际 BFGJ
53 000066.XSHE 中国长城 ZGCC
54 000068.XSHE 华控赛格 HKSG
55 000069.XSHE 华侨城A HQCA
56 000070.XSHE 特发信息 TFXX
57 000078.XSHE 海王生物 HWSW
58 000088.XSHE 盐田港 YTG
59 000089.XSHE 深圳机场 SZJC
60 000090.XSHE 天健集团 TJJT
61 000096.XSHE 广聚能源 GJNY
62 000099.XSHE 中信海直 ZXHZ
63 000100.XSHE TCL科技 TCLKJ
64 000150.XSHE *ST宜康 *STYK
65 000151.XSHE 中成股份 ZCGF
66 000153.XSHE 丰原药业 FYYY
67 000155.XSHE 川能动力 CNDL
68 000156.XSHE 华数传媒 HSCM
69 000157.XSHE 中联重科 ZLZK
70 000158.XSHE 常山北明 CSBM
71 000159.XSHE 国际实业 GJSY
72 000166.XSHE 申万宏源 SWHY
73 000301.XSHE 东方盛虹 DFSH
74 000333.XSHE 美的集团 MDJT
75 000338.XSHE 潍柴动力 WCDL
76 000400.XSHE 许继电气 XJDQ
77 000401.XSHE 金隅冀东 JYJD
78 000402.XSHE 金融街 JRJ
79 000403.XSHE 派林生物 PLSW
80 000404.XSHE 长虹华意 CHHY
81 000406.XSHE 石油大明 SYDM
82 000407.XSHE 胜利股份 SLGF
83 000408.XSHE 藏格矿业 CGKY
84 000409.XSHE 云鼎科技 YDKJ
85 000410.XSHE 沈阳机床 SYJC
86 000411.XSHE 英特集团 YTJT
87 000413.XSHE ST旭电 STXD
88 000415.XSHE 渤海租赁 BHZL
89 000416.XSHE *ST民控 *STMK
90 000417.XSHE 合百集团 HBJT
91 000418.XSHE 小天鹅A XTEA
92 000419.XSHE 通程控股 TCKG
93 000420.XSHE 吉林化纤 JLHX
94 000421.XSHE 南京公用 NJGY
95 000422.XSHE 湖北宜化 HBYH
96 000423.XSHE 东阿阿胶 DEEJ
97 000425.XSHE 徐工机械 XGJX
98 000426.XSHE 兴业银锡 XYYX
99 000428.XSHE 华天酒店 HTJD
100 000429.XSHE 粤高速A YGSA
101 000430.XSHE ST张家界 STZJJ
102 000488.XSHE ST晨鸣 STCM
103 000498.XSHE 山东路桥 SDLQ
104 000501.XSHE 武商集团 WSJT
105 000502.XSHE 绿景退 LJT
106 000503.XSHE 国新健康 GXJK
107 000504.XSHE *ST生物 *STSW
108 000505.XSHE 京粮控股 JLKG
109 000506.XSHE 招金黄金 ZJHJ
110 000507.XSHE 珠海港 ZHG
111 000509.XSHE 华塑控股 HSKG
112 000510.XSHE 新金路 XJL
113 000511.XSHE 烯碳退 XTT
114 000513.XSHE 丽珠集团 LZJT
115 000514.XSHE 渝开发 YKF
116 000515.XSHE 攀渝钛业 PYTY
117 000516.XSHE 国际医学 GJYX
118 000517.XSHE 荣安地产 RADC
119 000518.XSHE *ST四环 *STSH
120 000519.XSHE 中兵红箭 ZBHJ
121 000520.XSHE 凤凰航运 FHHY
122 000521.XSHE 长虹美菱 CHML
123 000522.XSHE 白云山A BYSA
124 000523.XSHE 红棉股份 HMGF
125 000524.XSHE 岭南控股 LNKG
126 000525.XSHE 红太阳 HTY
127 000526.XSHE 学大教育 XDJY
128 000527.XSHE 美的电器 MDDQ
129 000528.XSHE 柳工 LG
130 000529.XSHE 广弘控股 GHKG
131 000530.XSHE 冰山冷热 BSLR
132 000531.XSHE 穗恒运A SHYA
133 000532.XSHE 华金资本 HJZB
134 000533.XSHE 顺钠股份 SNGF
135 000534.XSHE 万泽股份 WZGF
136 000535.XSHE *ST猴王 *STHW
137 000536.XSHE 华映科技 HYKJ
138 000537.XSHE 绿发电力 LFDL
139 000538.XSHE 云南白药 YNBY
140 000539.XSHE 粤电力A YDLA
141 000540.XSHE *ST中天 *STZT
142 000541.XSHE 佛山照明 FSZM
143 000543.XSHE 皖能电力 WNDL
144 000544.XSHE 中原环保 ZYHB
145 000545.XSHE 金浦钛业 JPTY
146 000546.XSHE 金圆股份 JYGF
147 000547.XSHE 航天发展 HTFZ
148 000548.XSHE 湖南投资 HNTZ
149 000549.XSHE S湘火炬 SXHJ
150 000550.XSHE 江铃汽车 JLQC
151 000551.XSHE 创元科技 CYKJ
152 000552.XSHE 甘肃能化 GSNH
153 000553.XSHE 安道麦A ADMA
154 000554.XSHE 泰山石油 TSSY
155 000555.XSHE 神州信息 SZXX
156 000557.XSHE 西部创业 XBCY
157 000558.XSHE 天府文旅 TFWL
158 000559.XSHE 万向钱潮 WXQC
159 000560.XSHE 我爱我家 WAWJ
160 000561.XSHE 烽火电子 FHDZ
161 000562.XSHE 宏源证券 HYZQ
162 000563.XSHE 陕国投A SGTA
163 000564.XSHE 供销大集 GXDJ
164 000565.XSHE 渝三峡A YSXA
165 000566.XSHE 海南海药 HNHY
166 000567.XSHE 海德股份 HDGF
167 000568.XSHE 泸州老窖 LZLJ
168 000569.XSHE 长城股份 CCGF
169 000570.XSHE 苏常柴A SCCA
170 000571.XSHE 新大洲A XDZA
171 000572.XSHE 海马汽车 HMQC
172 000573.XSHE 粤宏远A YHYA
173 000576.XSHE 甘化科工 GHKG
174 000578.XSHE 盐湖集团 YHJT
175 000581.XSHE 威孚高科 WFGK
176 000582.XSHE 北部湾港 BBWG
177 000583.XSHE S*ST托普 S*STTP
178 000584.XSHE 工智退 GZT
179 000585.XSHE 东电退 DDT
180 000586.XSHE 汇源通信 HYTX
181 000587.XSHE *ST金洲 *STJZ
182 000589.XSHE 贵州轮胎 GZLT
183 000590.XSHE 古汉医药 GHYY
184 000591.XSHE 太阳能 TYN
185 000592.XSHE 平潭发展 PTFZ
186 000593.XSHE 德龙汇能 DLHN
187 000594.XSHE 国恒3 GHT
188 000595.XSHE *ST宝实 *STBS
189 000596.XSHE 古井贡酒 GJGJ
190 000597.XSHE 东北制药 DBZY
191 000598.XSHE 兴蓉环境 XRHJ
192 000599.XSHE 青岛双星 QDSX
193 000600.XSHE 建投能源 JTNY
194 000601.XSHE 韶能股份 SNGF
195 000602.XSHE 金马集团 JMJT
196 000603.XSHE 盛达资源 SDZY
197 000605.XSHE 渤海股份 BHGF
198 000606.XSHE 顺利退 SLT
199 000607.XSHE 华媒控股 HMKG
200 000608.XSHE *ST阳光 *STYG
201 000609.XSHE ST中迪 STZD
202 000610.XSHE 西安旅游 XALY
203 000611.XSHE 天首退 TST
204 000612.XSHE 焦作万方 JZWF
205 000613.XSHE 东海A退 DHAT
206 000615.XSHE *ST美谷 *STMG
207 000616.XSHE *ST海投 *STHT
208 000617.XSHE 中油资本 ZYZB
209 000618.XSHE 吉林化工 JLHG
210 000619.XSHE 海螺新材 HLXC
211 000620.XSHE 盈新发展 YXFZ
212 000622.XSHE 恒立退 HLT
213 000623.XSHE 吉林敖东 JLAD
214 000625.XSHE 长安汽车 CAQC
215 000626.XSHE 远大控股 YDKG
216 000627.XSHE *ST天茂 *STTM
217 000628.XSHE 高新发展 GXFZ
218 000629.XSHE 钒钛股份 FTGF
219 000630.XSHE 铜陵有色 TLYS
220 000631.XSHE 顺发恒能 SFHN
221 000632.XSHE 三木集团 SMJT
222 000633.XSHE 合金投资 HJTZ
223 000635.XSHE 英力特 YLT
224 000636.XSHE 风华高科 FHGK
225 000637.XSHE 茂化实华 MHSH
226 000638.XSHE *ST万方 *STWF
227 000639.XSHE 西王食品 XWSP
228 000650.XSHE 仁和药业 RHYY
229 000651.XSHE 格力电器 GLDQ
230 000652.XSHE 泰达股份 TDGF
231 000655.XSHE 金岭矿业 JLKY
232 000656.XSHE *ST金科 *STJK
233 000657.XSHE 中钨高新 ZWGX
234 000659.XSHE 珠海中富 ZHZF
235 000661.XSHE 长春高新 CCGX
236 000662.XSHE 天夏退 TXT
237 000663.XSHE 永安林业 YALY
238 000665.XSHE 湖北广电 HBGD
239 000666.XSHE 经纬纺机 JWFJ
240 000667.XSHE ST美置 STMZ
241 000668.XSHE *ST荣控 *STRK
242 000669.XSHE ST金鸿 STJH
243 000670.XSHE 盈方微 YFW
244 000671.XSHE ST阳光城 STYGC
245 000672.XSHE 上峰水泥 SFSN
246 000673.XSHE 当代退 DDT
247 000676.XSHE 智度股份 ZDGF
248 000677.XSHE 恒天海龙 HTHL
249 000678.XSHE 襄阳轴承 XYZC
250 000679.XSHE 大连友谊 DLYY
251 000680.XSHE 山推股份 STGF
252 000681.XSHE 视觉中国 SJZG
253 000682.XSHE 东方电子 DFDZ
254 000683.XSHE 博源化工 BYHG
255 000685.XSHE 中山公用 ZSGY
256 000686.XSHE 东北证券 DBZQ
257 000687.XSHE 华讯退 HXT
258 000688.XSHE 国城矿业 GCKY
259 000690.XSHE 宝新能源 BXNY
260 000691.XSHE *ST亚太 *STYT
261 000692.XSHE 惠天热电 HTRD
262 000693.XSHE 华泽退 HZT
263 000695.XSHE 滨海能源 BHNY
264 000697.XSHE ST炼石 STLS
265 000698.XSHE ST沈化 STSH
266 000699.XSHE S*ST佳纸 S*STJZ
267 000700.XSHE 模塑科技 MSKJ
268 000701.XSHE 厦门信达 XMXD
269 000702.XSHE 正虹科技 ZHKJ
270 000703.XSHE 恒逸石化 HYSH
271 000705.XSHE 浙江震元 ZJZY
272 000707.XSHE 双环科技 SHKJ
273 000708.XSHE 中信特钢 ZXTG
274 000709.XSHE 河钢股份 HGGF
275 000710.XSHE 贝瑞基因 BRJY
276 000711.XSHE ST京蓝 STJL
277 000712.XSHE 锦龙股份 JLGF
278 000713.XSHE 国投丰乐 GTFL
279 000715.XSHE 中兴商业 ZXSY
280 000716.XSHE 黑芝麻 HZM
281 000717.XSHE 中南股份 ZNGF
282 000718.XSHE 苏宁环球 SNHQ
283 000719.XSHE 中原传媒 ZYCM
284 000720.XSHE 新能泰山 XNTS
285 000721.XSHE 西安饮食 XAYS
286 000722.XSHE 湖南发展 HNFZ
287 000723.XSHE 美锦能源 MJNY
288 000725.XSHE 京东方A JDFA
289 000726.XSHE 鲁泰A LTA
290 000727.XSHE 冠捷科技 GJKJ
291 000728.XSHE 国元证券 GYZQ
292 000729.XSHE 燕京啤酒 YJPJ
293 000731.XSHE 四川美丰 SCMF
294 000732.XSHE ST泰禾 STTH
295 000733.XSHE 振华科技 ZHKJ
296 000735.XSHE 罗牛山 LNS
297 000736.XSHE *ST中地 *STZD
298 000737.XSHE 北方铜业 BFTY
299 000738.XSHE 航发控制 HFKZ
300 000739.XSHE 普洛药业 PLYY
301 000748.XSHE 长城信息 CCXX
302 000750.XSHE 国海证券 GHZQ
303 000751.XSHE 锌业股份 XYGF
304 000752.XSHE ST西发 STXF
305 000753.XSHE 漳州发展 ZZFZ
306 000755.XSHE 山西高速 SXGS
307 000756.XSHE 新华制药 XHZY
308 000757.XSHE 浩物股份 HWGF
309 000758.XSHE 中色股份 ZSGF
310 000759.XSHE 中百集团 ZBJT
311 000760.XSHE 斯太退 STT
312 000761.XSHE 本钢板材 BGBC
313 000762.XSHE 西藏矿业 XZKY
314 000763.XSHE 锦州石化 JZSH
315 000765.XSHE *ST华信 *STHX
316 000766.XSHE 通化金马 THJM
317 000767.XSHE 晋控电力 JKDL
318 000768.XSHE 中航西飞 ZHXF
319 000769.XSHE *ST大菲 *STDF
320 000776.XSHE 广发证券 GFZQ
321 000777.XSHE 中核科技 ZHKJ
322 000778.XSHE 新兴铸管 XXZG
323 000779.XSHE 甘咨询 GZX
324 000780.XSHE ST平能 STPN
325 000782.XSHE 恒申新材 HSXC
326 000783.XSHE 长江证券 CJZQ
327 000785.XSHE 居然智家 JRZJ
328 000786.XSHE 北新建材 BXJC
329 000787.XSHE *ST创智 *STCZ
330 000788.XSHE 北大医药 BDYY
331 000789.XSHE 万年青 WNQ
332 000790.XSHE 华神科技 HSKJ
333 000791.XSHE 甘肃能源 GSNY
334 000792.XSHE 盐湖股份 YHGF
335 000793.XSHE *ST华闻 *STHW
336 000795.XSHE 英洛华 YLH
337 000796.XSHE 凯撒旅业 KSLY
338 000797.XSHE 中国武夷 ZGWY
339 000798.XSHE 中水渔业 ZSYY
340 000799.XSHE 酒鬼酒 JGJ
341 000800.XSHE 一汽解放 YQJF
342 000801.XSHE 四川九洲 SCJZ
343 000802.XSHE 北京文化 BJWH
344 000803.XSHE 山高环能 SGHN
345 000805.XSHE *ST炎黄 *STYH
346 000806.XSHE 银河退 YHT
347 000807.XSHE 云铝股份 YLGF
348 000809.XSHE 和展能源 HZNY
349 000810.XSHE 创维数字 CWSZ
350 000811.XSHE 冰轮环境 BLHJ
351 000812.XSHE 陕西金叶 SXJY
352 000813.XSHE 德展健康 DZJK
353 000815.XSHE 美利云 MLY
354 000816.XSHE 智慧农业 ZHNY
355 000817.XSHE 辽河油田 LHYT
356 000818.XSHE 航锦科技 HJKJ
357 000819.XSHE 岳阳兴长 YYXC
358 000820.XSHE *ST节能 *STJN
359 000821.XSHE ST京机 STJJ
360 000822.XSHE 山东海化 SDHH
361 000823.XSHE 超声电子 CSDZ
362 000825.XSHE 太钢不锈 TGBX
363 000826.XSHE 启迪环境 QDHJ
364 000827.XSHE *ST长兴 *STCX
365 000828.XSHE 东莞控股 DGKG
366 000829.XSHE 天音控股 TYKG
367 000830.XSHE 鲁西化工 LXHG
368 000831.XSHE 中国稀土 ZGXT
369 000832.XSHE *ST龙涤 *STLD
370 000833.XSHE 粤桂股份 YGGF
371 000835.XSHE 长动退 CDT
372 000836.XSHE ST富通 STFT
373 000837.XSHE 秦川机床 QCJC
374 000838.XSHE 财信发展 CXFZ
375 000839.XSHE 国安股份 GAGF
376 000848.XSHE 承德露露 CDLL
377 000850.XSHE 华茂股份 HMGF
378 000851.XSHE *ST高鸿 *STGH
379 000852.XSHE 石化机械 SHJX
380 000856.XSHE 冀东装备 JDZB
381 000858.XSHE 五粮液 WLY
382 000859.XSHE 国风新材 GFXC
383 000860.XSHE 顺鑫农业 SXNY
384 000861.XSHE 海印股份 HYGF
385 000862.XSHE 银星能源 YXNY
386 000863.XSHE 三湘印象 SXYX
387 000866.XSHE 扬子石化 YZSH
388 000868.XSHE 安凯客车 AKKC
389 000869.XSHE 张裕A ZYA
390 000875.XSHE 电投绿能 DTLN
391 000876.XSHE 新希望 XXW
392 000877.XSHE 天山股份 TSGF
393 000878.XSHE 云南铜业 YNTY
394 000880.XSHE 潍柴重机 WCZJ
395 000881.XSHE 中广核技 ZGHJ
396 000882.XSHE 华联股份 HLGF
397 000883.XSHE 湖北能源 HBNY
398 000885.XSHE 城发环境 CFHJ
399 000886.XSHE 海南高速 HNGS
400 000887.XSHE 中鼎股份 ZDGF
401 000888.XSHE 峨眉山A EMSA
402 000889.XSHE 中嘉博创 ZJBC
403 000890.XSHE 法尔胜 FES
404 000892.XSHE 欢瑞世纪 HRSJ
405 000893.XSHE 亚钾国际 YJGJ
406 000895.XSHE 双汇发展 SHFZ
407 000897.XSHE 津滨发展 JBFZ
408 000898.XSHE 鞍钢股份 AGGF
409 000899.XSHE 赣能股份 GNGF
410 000900.XSHE 现代投资 XDTZ
411 000901.XSHE 航天科技 HTKJ
412 000902.XSHE 新洋丰 XYF
413 000903.XSHE ST云动 STYD
414 000905.XSHE 厦门港务 XMGW
415 000906.XSHE 浙商中拓 ZSZT
416 000908.XSHE ST景峰 STJF
417 000909.XSHE *ST数源 *STSY
418 000910.XSHE 大亚圣象 DYSX
419 000911.XSHE 广农糖业 GNTY
420 000912.XSHE 泸天化 LTH
421 000913.XSHE 钱江摩托 QJMT
422 000915.XSHE 华特达因 HTDY
423 000916.XSHE 华北高速 HBGS
424 000917.XSHE 电广传媒 DGCM
425 000918.XSHE *ST嘉凯 *STJK
426 000919.XSHE 金陵药业 JLYY
427 000920.XSHE 沃顿科技 WDKJ
428 000921.XSHE 海信家电 HXJD
429 000922.XSHE 佳电股份 JDGF
430 000923.XSHE 河钢资源 HGZY
431 000925.XSHE 众合科技 ZHKJ
432 000926.XSHE 福星股份 FXGF
433 000927.XSHE 中国铁物 ZGTW
434 000928.XSHE 中钢国际 ZGGJ
435 000929.XSHE *ST兰黄 *STLH
436 000930.XSHE 中粮科技 ZLKJ
437 000931.XSHE 中关村 ZGC
438 000932.XSHE 华菱钢铁 HLGT
439 000933.XSHE 神火股份 SHGF
440 000935.XSHE 四川双马 SCSM
441 000936.XSHE 华西股份 HXGF
442 000937.XSHE 冀中能源 JZNY
443 000938.XSHE 紫光股份 ZGGF
444 000939.XSHE 凯迪退 KDT
445 000948.XSHE 南天信息 NTXX
446 000949.XSHE 新乡化纤 XXHX
447 000950.XSHE 重药控股 CYKG
448 000951.XSHE 中国重汽 ZGZQ
449 000952.XSHE 广济药业 GJYY
450 000953.XSHE 河化股份 HHGF
451 000955.XSHE 欣龙控股 XLKG
452 000956.XSHE 中原油气 ZYYQ
453 000957.XSHE 中通客车 ZTKC
454 000958.XSHE 电投产融 DTCR
455 000959.XSHE 首钢股份 SGGF
456 000960.XSHE 锡业股份 XYGF
457 000961.XSHE ST中南 STZN
458 000962.XSHE 东方钽业 DFTY
459 000963.XSHE 华东医药 HDYY
460 000965.XSHE 天保基建 TBJJ
461 000966.XSHE 长源电力 CYDL
462 000967.XSHE 盈峰环境 YFHJ
463 000968.XSHE 蓝焰控股 LYKG
464 000969.XSHE 安泰科技 ATKJ
465 000970.XSHE 中科三环 ZKSH
466 000971.XSHE *ST高升 *STGS
467 000972.XSHE *ST中基 *STZJ
468 000973.XSHE 佛塑科技 FSKJ
469 000975.XSHE 山金国际 SJGJ
470 000976.XSHE *ST华铁 *STHT
471 000977.XSHE 浪潮信息 LCXX
472 000978.XSHE 桂林旅游 GLLY
473 000979.XSHE 中弘退 ZHT
474 000980.XSHE 众泰汽车 ZTQC
475 000981.XSHE 山子高科 SZGK
476 000982.XSHE 中银绒业 ZYRY
477 000983.XSHE 山西焦煤 SXJM
478 000985.XSHE 大庆华科 DQHK
479 000987.XSHE 越秀资本 YXZB
480 000988.XSHE 华工科技 HGKJ
481 000989.XSHE 九芝堂 JZT
482 000990.XSHE 诚志股份 CZGF
483 000993.XSHE 闽东电力 MDDL
484 000995.XSHE 皇台酒业 HTJY
485 000996.XSHE 中期退 ZQT
486 000997.XSHE 新大陆 XDL
487 000998.XSHE 隆平高科 LPGK
488 000999.XSHE 华润三九 HRSJ
489 001201.XSHE 东瑞股份 DRGF
490 001202.XSHE 炬申股份 JSGF
491 001203.XSHE 大中矿业 DZKY
492 001205.XSHE 盛航股份 SHGF
493 001206.XSHE 依依股份 YYGF
494 001207.XSHE 联科科技 LKKJ
495 001208.XSHE 华菱线缆 HLXL
496 001209.XSHE 洪兴股份 HXGF
497 001210.XSHE 金房能源 JFNY
498 001211.XSHE 双枪科技 SQKJ
499 001212.XSHE 中旗新材 ZQXC
500 001213.XSHE 中铁特货 ZTTH
501 001215.XSHE 千味央厨 QWYC
502 001216.XSHE 华瓷股份 HCGF
503 001217.XSHE 华尔泰 HET
504 001218.XSHE 丽臣实业 LCSY
505 001219.XSHE 青岛食品 QDSP
506 001220.XSHE 世盟股份 SMGF
507 001221.XSHE 悍高集团 HGJT
508 001222.XSHE 源飞宠物 YFCW
509 001223.XSHE 欧克科技 OKKJ
510 001225.XSHE 和泰机电 HTJD
511 001226.XSHE 拓山重工 TSZG
512 001227.XSHE 兰州银行 LZYX
513 001228.XSHE 永泰运 YTY
514 001229.XSHE 魅视科技 MSKJ
515 001230.XSHE 劲旅环境 JLHJ
516 001231.XSHE 农心科技 NXKJ
517 001233.XSHE 海安集团 HAJT
518 001234.XSHE 泰慕士 TMS
519 001236.XSHE 弘业期货 HYQH
520 001238.XSHE 浙江正特 ZJZT
521 001239.XSHE 永达股份 YDGF
522 001255.XSHE 博菲电气 BFDQ
523 001256.XSHE 炜冈科技 WGKJ
524 001257.XSHE 盛龙股份 SLGF
525 001258.XSHE 立新能源 LXNY
526 001259.XSHE 利仁科技 LRKJ
527 001260.XSHE 坤泰股份 KTGF
528 001266.XSHE 宏英智能 HYZN
529 001267.XSHE 汇绿生态 HLST
530 001268.XSHE 联合精密 LHJM
531 001269.XSHE 欧晶科技 OJKJ
532 001270.XSHE *ST铖昌 *STCC
533 001277.XSHE 速达股份 SDGF
534 001278.XSHE 一彬科技 YBKJ
535 001279.XSHE 强邦新材 QBXC
536 001280.XSHE 中国铀业 ZGYY
537 001282.XSHE 三联锻造 SLDZ
538 001283.XSHE 豪鹏科技 HPKJ
539 001285.XSHE 瑞立科密 RLKM
540 001286.XSHE 陕西能源 SXNY
541 001287.XSHE 中电港 ZDG
542 001288.XSHE 运机集团 YJJT
543 001289.XSHE 龙源电力 LYDL
544 001296.XSHE 长江材料 CJCL
545 001298.XSHE 好上好 HSH
546 001299.XSHE 美能能源 MNNY
547 001300.XSHE 三柏硕 SBS
548 001301.XSHE 尚太科技 STKJ
549 001306.XSHE 夏厦精密 XSJM
550 001308.XSHE 康冠科技 KGKJ
551 001309.XSHE 德明利 DML
552 001311.XSHE 多利科技 DLKJ
553 001313.XSHE 粤海饲料 YHSL
554 001314.XSHE 亿道信息 YDXX
555 001316.XSHE 润贝航科 RBHK
556 001317.XSHE 三羊马 SYM
557 001318.XSHE 阳光乳业 YGRY
558 001319.XSHE 铭科精技 MKJJ
559 001322.XSHE 箭牌家居 JPJJ
560 001323.XSHE 慕思股份 MSGF
561 001324.XSHE 长青科技 CQKJ
562 001325.XSHE 元创股份 YCGF
563 001326.XSHE 联域股份 LYGF
564 001328.XSHE 登康口腔 DKKQ
565 001330.XSHE 博纳影业 BNYY
566 001331.XSHE 胜通能源 STNY
567 001332.XSHE 锡装股份 XZGF
568 001333.XSHE 光华股份 GHGF
569 001335.XSHE 信凯科技 XKKJ
570 001336.XSHE 楚环科技 CHKJ
571 001337.XSHE 四川黄金 SCHJ
572 001338.XSHE 永顺泰 YST
573 001339.XSHE 智微智能 ZWZN
574 001356.XSHE 富岭股份 FLGF
575 001358.XSHE 兴欣新材 XXXC
576 001359.XSHE 平安电工 PADG
577 001360.XSHE 南矿集团 NKJT
578 001366.XSHE 播恩集团 BEJT
579 001367.XSHE 海森药业 HSYY
580 001368.XSHE 通达创智 TDCZ
581 001369.XSHE 双欣材料 SXCL
582 001373.XSHE 翔腾新材 XTXC
583 001376.XSHE 百通能源 BTNY
584 001378.XSHE 德冠新材 DGXC
585 001379.XSHE 腾达科技 TDKJ
586 001380.XSHE 华纬科技 HWKJ
587 001382.XSHE 新亚电缆 XYDL
588 001386.XSHE 马可波罗 MKBL
589 001387.XSHE 雪祺电气 XQDQ
590 001388.XSHE 信通电子 XTDZ
591 001389.XSHE 广合科技 GHKJ
592 001390.XSHE 古麒绒材 GQRC
593 001391.XSHE 国货航 GHH
594 001395.XSHE 亚联机械 YLJX
595 001396.XSHE 誉帆科技 YFKJ
596 001400.XSHE 江顺科技 JSKJ
597 001696.XSHE 宗申动力 ZSDL
598 001872.XSHE 招商港口 ZSGK
599 001896.XSHE 豫能控股 YNKG
600 001914.XSHE 招商积余 ZSJY
601 001965.XSHE 招商公路 ZSGL
602 001979.XSHE 招商蛇口 ZSSK
603 002001.XSHE 新和成 XHC
604 002002.XSHE ST鸿达 STHD
605 002003.XSHE 伟星股份 WXGF
606 002004.XSHE 华邦健康 HBJK
607 002005.XSHE ST德豪 STDH
608 002006.XSHE 精工科技 JGKJ
609 002007.XSHE 华兰生物 HLSW
610 002008.XSHE 大族激光 DZJG
611 002009.XSHE 天奇股份 TQGF
612 002010.XSHE 传化智联 CHZL
613 002011.XSHE 盾安环境 DAHJ
614 002012.XSHE 凯恩股份 KEGF
615 002013.XSHE 中航机电 ZHJD
616 002014.XSHE 永新股份 YXGF
617 002015.XSHE 协鑫能科 XXNK
618 002016.XSHE 世荣兆业 SRZY
619 002017.XSHE 东信和平 DXHP
620 002018.XSHE 华信退 HXT
621 002019.XSHE 亿帆医药 YFYY
622 002020.XSHE 京新药业 JXYY
623 002021.XSHE 中捷资源 ZJZY
624 002022.XSHE 科华生物 KHSW
625 002023.XSHE 海特高新 HTGX
626 002024.XSHE ST易购 STYG
627 002025.XSHE 航天电器 HTDQ
628 002026.XSHE 山东威达 SDWD
629 002027.XSHE 分众传媒 FZCM
630 002028.XSHE 思源电气 SYDQ
631 002029.XSHE 七匹狼 QPL
632 002030.XSHE 达安基因 DAJY
633 002031.XSHE 巨轮智能 JLZN
634 002032.XSHE 苏泊尔 SBE
635 002033.XSHE 丽江股份 LJGF
636 002034.XSHE 旺能环境 WNHJ
637 002035.XSHE 华帝股份 HDGF
638 002036.XSHE 联创电子 LCDZ
639 002037.XSHE 保利联合 BLLH
640 002038.XSHE 双鹭药业 SLYY
641 002039.XSHE 黔源电力 QYDL
642 002040.XSHE 南京港 NJG
643 002041.XSHE 登海种业 DHZY
644 002042.XSHE 华孚时尚 HFSS
645 002043.XSHE 兔宝宝 TBB
646 002044.XSHE 美年健康 MNJK
647 002045.XSHE 国光电器 GGDQ
648 002046.XSHE 国机精工 GJJG
649 002047.XSHE *ST宝鹰 *STBY
650 002048.XSHE 宁波华翔 NBHX
651 002049.XSHE 紫光国微 ZGGW
652 002050.XSHE 三花智控 SHZK
653 002051.XSHE 中工国际 ZGGJ
654 002052.XSHE 同洲电子 TZDZ
655 002053.XSHE 云南能投 YNNT
656 002054.XSHE 德美化工 DMHG
657 002055.XSHE ST得润 STDR
658 002056.XSHE 横店东磁 HDDC
659 002057.XSHE 中钢天源 ZGTY
660 002058.XSHE *ST威尔 *STWE
661 002059.XSHE 云南旅游 YNLY
662 002060.XSHE 广东建工 GDJG
663 002061.XSHE 浙江交科 ZJJK
664 002062.XSHE 宏润建设 HRJS
665 002063.XSHE 远光软件 YGRJ
666 002064.XSHE 华峰化学 HFHX
667 002065.XSHE 东华软件 DHRJ
668 002066.XSHE 瑞泰科技 RTKJ
669 002067.XSHE 景兴纸业 JXZY
670 002068.XSHE 黑猫股份 HMGF
671 002069.XSHE 獐子岛 ZZD
672 002070.XSHE 众和退 ZHT
673 002071.XSHE 长城退 CCT
674 002072.XSHE 凯瑞德 KRD
675 002073.XSHE 软控股份 RKGF
676 002074.XSHE 国轩高科 GXGK
677 002075.XSHE 沙钢股份 SGGF
678 002076.XSHE *ST星光 *STXG
679 002077.XSHE 大港股份 DGGF
680 002078.XSHE 太阳纸业 TYZY
681 002079.XSHE 苏州固锝 SZGD
682 002080.XSHE 中材科技 ZCKJ
683 002081.XSHE 金螳螂 JTL
684 002082.XSHE 万邦德 WBD
685 002083.XSHE 孚日股份 FRGF
686 002084.XSHE 海鸥住工 HOZG
687 002085.XSHE 万丰奥威 WFAW
688 002086.XSHE 东方海洋 DFHY
689 002087.XSHE 新纺退 XFT
690 002088.XSHE 鲁阳节能 LYJN
691 002089.XSHE 新海退 XHT
692 002090.XSHE 金智科技 JZKJ
693 002091.XSHE 江苏国泰 JSGT
694 002092.XSHE 中泰化学 ZTHX
695 002093.XSHE 国脉科技 GMKJ
696 002094.XSHE 青岛金王 QDJW
697 002095.XSHE 生意宝 SYB
698 002096.XSHE 易普力 YPL
699 002097.XSHE 山河智能 SHZN
700 002098.XSHE 浔兴股份 XXGF
701 002099.XSHE 海翔药业 HXYY
702 002100.XSHE 天康生物 TKSW
703 002101.XSHE 广东鸿图 GDHT
704 002102.XSHE 能特科技 NTKJ
705 002103.XSHE 广博股份 GBGF
706 002104.XSHE 恒宝股份 HBGF
707 002105.XSHE 信隆健康 XLJK
708 002106.XSHE 莱宝高科 LBGK
709 002107.XSHE 沃华医药 WHYY
710 002108.XSHE 沧州明珠 CZMZ
711 002109.XSHE 兴化股份 XHGF
712 002110.XSHE 三钢闽光 SGMG
713 002111.XSHE 威海广泰 WHGT
714 002112.XSHE 三变科技 SBKJ
715 002113.XSHE *ST天润 *STTR
716 002114.XSHE 罗平锌电 LPXD
717 002115.XSHE 三维通信 SWTX
718 002116.XSHE 中国海诚 ZGHC
719 002117.XSHE 东港股份 DGGF
720 002118.XSHE *ST紫鑫 *STZX
721 002119.XSHE 康强电子 KQDZ
722 002120.XSHE 韵达股份 YDGF
723 002121.XSHE 科陆电子 KLDZ
724 002122.XSHE ST汇洲 STHZ
725 002123.XSHE 梦网科技 MWKJ
726 002124.XSHE 天邦食品 TBSP
727 002125.XSHE 湘潭电化 XTDH
728 002126.XSHE 银轮股份 YLGF
729 002127.XSHE 南极电商 NJDS
730 002128.XSHE 电投能源 DTNY
731 002129.XSHE TCL中环 TCLZH
732 002130.XSHE 沃尔核材 WEHC
733 002131.XSHE 利欧股份 LOGF
734 002132.XSHE 恒星科技 HXKJ
735 002133.XSHE 广宇集团 GYJT
736 002134.XSHE 天津普林 TJPL
737 002135.XSHE 东南网架 DNWJ
738 002136.XSHE 安纳达 AND
739 002137.XSHE 实益达 SYD
740 002138.XSHE 顺络电子 SLDZ
741 002139.XSHE 拓邦股份 TBGF
742 002140.XSHE 东华科技 DHKJ
743 002141.XSHE 贤丰控股 XFKG
744 002142.XSHE 宁波银行 NBYH
745 002143.XSHE 印纪退 YJT
746 002144.XSHE 宏达高科 HDGK
747 002145.XSHE 钛能化学 TNHX
748 002146.XSHE 荣盛发展 RSFZ
749 002147.XSHE 新光退 XGT
750 002148.XSHE 北纬科技 BWKJ
751 002149.XSHE 西部材料 XBCL
752 002150.XSHE 正泰电源 ZTDY
753 002151.XSHE 北斗星通 BDXT
754 002152.XSHE 广电运通 GDYT
755 002153.XSHE 石基信息 SJXX
756 002154.XSHE 报喜鸟 BXN
757 002155.XSHE 湖南黄金 HNHJ
758 002156.XSHE 通富微电 TFWD
759 002157.XSHE 正邦科技 ZBKJ
760 002158.XSHE 汉钟精机 HZJJ
761 002159.XSHE 三特索道 STSD
762 002160.XSHE 常铝股份 CLGF
763 002161.XSHE 远望谷 YWG
764 002162.XSHE 悦心健康 YXJK
765 002163.XSHE 海南发展 HNFZ
766 002164.XSHE 宁波东力 NBDL
767 002165.XSHE 红宝丽 HBL
768 002166.XSHE 莱茵生物 LYSW
769 002167.XSHE 东方锆业 DFGY
770 002168.XSHE *ST惠程 *STHC
771 002169.XSHE 智光电气 ZGDQ
772 002170.XSHE 芭田股份 BTGF
773 002171.XSHE 楚江新材 CJXC
774 002172.XSHE 澳洋健康 AYJK
775 002173.XSHE 创新医疗 CXYL

,open,high,low,close,pre_close,high_limit,low_limit,avg,volume,datetime,symbol,amount,paused
0,33.00,49.80,33.00,38.50,18.94,10000.00,0.01,38.68,40954922.00,2020-10-29,689009.XSHG,1.584101e+09,0.0
1,40.02,51.56,40.02,47.60,38.50,10000.00,0.01,45.12,33600551.00,2020-10-30,689009.XSHG,1.515931e+09,0.0
2,50.20,56.78,48.81,56.77,47.60,10000.00,0.01,52.52,27193402.00,2020-11-02,689009.XSHG,1.428223e+09,0.0
3,56.50,59.55,53.36,57.39,56.77,10000.00,0.01,56.10,25121445.00,2020-11-03,689009.XSHG,1.409432e+09,0.0
4,57.45,57.80,51.90,54.40,57.39,10000.00,0.01,54.61,20846450.00,2020-11-04,689009.XSHG,1.138491e+09,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1316,45.25,46.29,44.93,45.74,44.93,53.92,35.94,45.78,10123365.96,2026-04-03,689009.XSHG,4.634248e+08,0.0
1317,46.08,46.53,45.31,45.78,45.74,54.89,36.60,45.82,7797372.56,2026-04-07,689009.XSHG,3.572396e+08,0.0
1318,46.60,47.81,46.53,46.86,45.78,54.94,36.63,46.94,11912363.02,2026-04-08,689009.XSHG,5.591853e+08,0.0
1319,46.58,46.99,46.09,46.40,46.86,56.23,37.49,46.43,7180999.58,2026-04-09,689009.XSHG,3.333779e+08,0.0
1320,46.60,47.30,46.17,46.26,46.40,55.68,37.12,46.62,10077428.43,2026-04-10,689009.XSHG,4.698160e+08,0.0